; Pavel Penkov 2025 All Rights Reserved.
; UUHLConvention moved from ConventionKeeperEditor to ConventionKeeperConventions module.

[CoreRedirects]
+ClassRedirects=(OldName="UUHLConvention",NewName="UUHLConvention",NewPackageName="ConventionKeeperConventions",OldPackageName="ConventionKeeperEditor")
